@RestaurantsAPI_HostAddress = http://localhost:5293
@token = CfDJ8Ib2g0MYGkJMtazJcRgLALFIVGUeXl6p1h2_k5yFFCiDsXKoNXFZAJJYDnZVgcjnTL-0jbqr0P9AagufmCdlCfXtqWjXbdWuosGYDRFJ9VdPceUZXw1xFaMrZQ8pO9zezu5uSfzVmcTjNbOcrYF_4vui_zzupLzdkHjtxdCLl6WA4ynyIZQqI-1xlxEkDoFs7y77Dts92bGD_DKXarP9Hu0qo5UFFpwRXOIFEqhk2oQipwDdbas0CNEHblaDOnOqh8JBIgrpD3Jrqfh5Vw30-X1Wggl1q6xWv9Ek_QvQ24HJsmAydTDdQuzdV9jbtYXV8_0UVTIwA98NtV1W8CoYCiRtF7sK9OCgOF7Sb4G-GJDQTcLpoFFk4AnSfYe26z-wHz2QOkkzhz0kH6o7hr-BnaP1lXcuZR44qz_Kh_hABq0z-Lo3rsZG2uUY3cRzeA1qdu-qwci4R3WSH2bCsUk-kZ61dF4lUQSKgQpBxF2526BYwoOu05w_txCTYYY30NhEwlbhi55w2M4COU3GXWYldpPxdyrIRoPJBPi2Wl8GoJKYZ7mjKgFyExRkNpcYZH-36vPzbpZ8z3mxwsHVDxH9VJgYgMT2vT6KGZMmMCSLZZQLfM5eh6Skc5w7An2ZFsPtMA6dXniU38zYhMPvR4DjAw9zMtAH1XzDGg4QkU8nTMgwWZYgw--aMhnmKJ3Y-Bsbm-9jfpeur9RA0UeJlRYmRTVelNpL3XzZNU1kmBAvwy8dE6RseVMALaR9MKJt01Fw4aYzOo3erUXKbZqOq6ysWFOlzxuXAddc2CLZbeGJaGYX

GET {{RestaurantsAPI_HostAddress}}/api/restaurants
Accept: application/json
#Authorization: Bearer {{token}}

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3af987b0-e8ca-4293-ebc5-08dcea06ac45
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{RestaurantsAPI_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "City Wok",
  "description": "The world's best Chinese food",
  "category": "Chinese",
  "hasDelivery": true,
  "contactEmail": "bruce.lee@chinese-spy.com",
  "contactNumber": "123-456-7890",
  "city": "South Park",
  "street": "Main Street",
  "postalCode": "22-333"
}

###

DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/97ca1637-93ea-4b1c-85dd-91e2a253fa3d
Accept: application/json

###

PATCH {{RestaurantsAPI_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "id": "97ca1637-93ea-4b1c-85dd-91e2a253fa3d",
  "name": "City Sushi 1",
  "description": "The most authentic Japanese cuisine in the region",
  "hasDelivery": true
}

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/54a3718d-9cb5-48e1-81f3-c29673125bcb/dishes
Accept: application/json

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3af987b0-e8ca-4293-ebc5-08dcea06ac45/dishes/c4c23fee-61d9-418d-ad02-08dcea06ac4d
Accept: application/json

###

POST {{RestaurantsAPI_HostAddress}}/api/restaurants/54a3718d-9cb5-48e1-81f3-c29673125bcb/dishes
Content-Type: application/json

{
  "name": "Chicken Kadai",
  "description": "A spicy chicken delicacy",
  "price": 24.99,
  "kiloCalories": 520
}

###

PATCH {{RestaurantsAPI_HostAddress}}/api/restaurants/54a3718d-9cb5-48e1-81f3-c29673125bcb/dishes/
Content-Type: application/json

{
  "id": "AAFCCE92-4E96-48F8-A1C8-0C92C344241F",
  "name": "Chicken Kadai",
  "description": "Yet another disgusting indian dish with low nutritional value and high calories",
  "price": 49.99,
  "kiloCalories": 600
}

###

DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/54a3718d-9cb5-48e1-81f3-c29673125bcb/dishes/aafcce92-4e96-48f8-a1c8-0c92c344241f
Accept: application/json

###

POST {{RestaurantsAPI_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@example.com",
  "password": "Hello@1234"
}

###

POST {{RestaurantsAPI_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Hello@1234"
}

###

PATCH {{RestaurantsAPI_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "dateOfBirth": "1960-12-16",
  "nationality": "RSA"
}

###

POST {{RestaurantsAPI_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userEmail": "john.doe@example.com",
  "roleName": "Owner"
}