@RestaurantsAPI_HostAddress = http://localhost:5293

GET {{RestaurantsAPI_HostAddress}}/api/restaurants
Accept: application/json

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/97ca1637-93ea-4b1c-85dd-91e2a253fa3d
Accept: application/json

###

POST {{RestaurantsAPI_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "City Wok",
  "description": "The world's best Chinese food",
  "category": "Chinese",
  "hasDelivery": true,
  "contactEmail": "bruce.lee@chinese-spy.com",
  "contactNumber": "123-456-7890",
  "city": "South Park",
  "street": "Main Street",
  "postalCode": "22-333"
}

###

DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/97ca1637-93ea-4b1c-85dd-91e2a253fa3d
Accept: application/json

###

PATCH {{RestaurantsAPI_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "id": "97ca1637-93ea-4b1c-85dd-91e2a253fa3d",
  "name": "City Sushi 1",
  "description": "The most authentic Japanese cuisine in the region",
  "hasDelivery": true
}

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/fce7262b-74b7-424e-ac7c-7e340c923f26/dishes
Accept: application/json

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3af987b0-e8ca-4293-ebc5-08dcea06ac45/dishes/c4c23fee-61d9-418d-ad02-08dcea06ac4d
Accept: application/json

###

POST {{RestaurantsAPI_HostAddress}}/api/restaurants/fce7262b-74b7-424e-ac7c-7e340c923f26/dishes
Content-Type: application/json

{
  "restaurantId": "fce7262b-74b7-424e-ac7c-7e340c923f26",
  "name": "Chicken Kadai",
  "description": "A spicy chicken delicacy",
  "price": 24.99,
  "kiloCalories": 520
}

###