@RestaurantsAPI_HostAddress = http://localhost:5293

GET {{RestaurantsAPI_HostAddress}}/api/restaurants
Accept: application/json

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/423156fb-a4b1-46d2-605d-08dce7093456
Accept: application/json

###

POST {{RestaurantsAPI_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "City Wok",
  "description": "The world's best Chinese food",
  "category": "Chinese",
  "hasDelivery": true,
  "contactEmail": "bruce.lee@chinese-spy.com",
  "contactNumber": "123-456-7890",
  "city": "South Park",
  "street": "Main Street",
  "postalCode": "22-333"
}

###

DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/2ce80d73-e95c-4ce5-b952-4863d014aebd
Accept: application/json

###

PATCH {{RestaurantsAPI_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "id": "2baf1d85-f316-46b0-8944-1831dd0464cc",
  "name": "City Sushi 1",
  "description": "The most authentic Japanese cuisine in the region",
  "hasDelivery": true
}